# Nikolaisen2022 bin 00: smallest filtered Plag STL files

Evaluate surface quality, convert filtered Plag STL files to tetrahedral Gmsh `.msh` meshes with the Gmsh Delaunay 3D algorithm, print mesh quality and Merrill.jl memory estimates, and display a limited set of converted meshes with PyVista.

In [8]:
from pathlib import Path
import sys

REPO = Path.cwd()
if not (REPO / "src").exists() and (REPO.parent / "src").exists():
    REPO = REPO.parent
sys.path.insert(0, str(REPO / "src"))

from stl2fem.datasets import add_nikolaisen_stl_metadata, assign_size_bins, nikolaisen_inventory
from stl2fem.visualize import display_volume_mesh
from stl2fem.conversion import DEFAULT_BRUTE_FORCE_MAX_CELLS_PER_AXIS
from stl2fem.workflow import DEFAULT_MESH_STRATEGIES, DEFAULT_MESH_TIMEOUT_SECONDS, process_nikolaisen_size_bin

DATASET_ROOT = REPO / "data" / "Nikolaisen2022"
OUTPUT_ROOT = REPO / "data" / "Nikolaisen2022_merrill_msh"
BIN_INDEX = 0
N_BINS = 4
INPUT_UNIT = "um"
TARGET_EDGE_LENGTH_M = 9e-9
PHASES = ("PLAG",)
MAX_EVSD_UM = 1.0
SAVE_NATIVE_MESH = False
MESH_TIMEOUT_SECONDS = DEFAULT_MESH_TIMEOUT_SECONDS
MESH_STRATEGIES = DEFAULT_MESH_STRATEGIES
BRUTEFORCE_MAX_CELLS_PER_AXIS = DEFAULT_BRUTE_FORCE_MAX_CELLS_PER_AXIS
OVERWRITE = False
MAX_MESHES = None
DISPLAY_LIMIT = 100

In [6]:
inventory = add_nikolaisen_stl_metadata(
    nikolaisen_inventory(DATASET_ROOT, phases=PHASES),
    dataset_root=DATASET_ROOT,
)
inventory = inventory[inventory["metadata_evsd_um"] < MAX_EVSD_UM].copy()
inventory = assign_size_bins(inventory, n_bins=N_BINS)
subset = inventory[inventory["size_bin_index"] == BIN_INDEX]
print(f"Meshes in this notebook: {len(subset)}")
subset[[
    "particle_id", "phase", "stl_format", "metadata_evsd_um",
    "stl_size_mib", "size_bin", "source_path",
]]

Meshes in this notebook: 62

,particle_id,phase,stl_format,metadata_evsd_um,stl_size_mib,size_bin,source_path
0,PLAG246,PLAG,ascii,0.041881,0.006841,00_smallest,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
1,PLAG245,PLAG,ascii,0.044774,0.007753,00_smallest,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
2,PLAG244,PLAG,ascii,0.043393,0.008069,00_smallest,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
3,PLAG243,PLAG,ascii,0.038427,0.008540,00_smallest,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
4,PLAG242,PLAG,ascii,0.039649,0.008695,00_smallest,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
...,...,...,...,...,...,...,...
57,PLAG189,PLAG,ascii,0.063722,0.024453,00_smallest,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
58,PLAG188,PLAG,ascii,0.091994,0.024759,00_smallest,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
59,PLAG187,PLAG,ascii,0.090067,0.024917,00_smallest,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
60,PLAG186,PLAG,ascii,0.087993,0.025535,00_smallest,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
61,PLAG184,PLAG,ascii,0.081315,0.025689,00_smallest,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...

In [3]:
results = process_nikolaisen_size_bin(
    DATASET_ROOT,
    OUTPUT_ROOT,
    bin_index=BIN_INDEX,
    n_bins=N_BINS,
    input_unit=INPUT_UNIT,
    target_edge_length_m=TARGET_EDGE_LENGTH_M,
    phases=PHASES,
    max_evsd_um=MAX_EVSD_UM,
    save_native_mesh=SAVE_NATIVE_MESH,
    mesh_timeout_seconds=MESH_TIMEOUT_SECONDS,
    mesh_strategies=MESH_STRATEGIES,
    bruteforce_max_cells_per_axis=BRUTEFORCE_MAX_CELLS_PER_AXIS,
    overwrite=OVERWRITE,
    max_meshes=MAX_MESHES,
)

columns = [
    "particle_id", "phase", "status", "metadata_evsd_um", "stl_size_mib",
    "merrill_msh_size_bytes", "merrill_msh_size_mib",
    "input_unit", "input_scale_to_meters", "target_edge_length_m", "target_edge_length_native",
    "edge_length_median", "edge_length_p95", "edge_length_median_m", "edge_length_p95_m",
    "n_nodes", "n_tets", "volume_min", "scaled_jacobian_min",
    "radius_ratio_max", "estimated_memory_human", "msh_path", "merrill_msh_path",
]
available = [column for column in columns if column in results.columns]
results[available]

2026-05-03 16:04:04.487 (   0.121s) [          6A9287]  vtkMassProperties.cxx:60     ERR| vtkMassProperties (0x110f50bc0): No data to measure...!
ERROR:root:No data to measure...!

,particle_id,phase,status,metadata_evsd_um,stl_size_mib,merrill_msh_size_bytes,merrill_msh_size_mib,input_unit,input_scale_to_meters,target_edge_length_m,...,edge_length_median_m,edge_length_p95_m,n_nodes,n_tets,volume_min,scaled_jacobian_min,radius_ratio_max,estimated_memory_human,msh_path,merrill_msh_path
0,PLAG246,PLAG,ok,0.041881,0.006841,29496,0.028130,um,0.000001,9.000000e-09,...,8.660598e-09,1.323955e-08,272,776,1.357760e-08,0.172251,3.315044,1.76 MiB,None,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
1,PLAG245,PLAG,ok,0.044774,0.007753,31008,0.029572,um,0.000001,9.000000e-09,...,8.946291e-09,1.342828e-08,283,819,1.290173e-08,0.196985,3.271441,1.83 MiB,None,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
2,PLAG244,PLAG,ok,0.043393,0.008069,33080,0.031548,um,0.000001,9.000000e-09,...,8.762164e-09,1.346733e-08,305,871,1.196371e-08,0.212135,3.223637,1.97 MiB,None,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
3,PLAG243,PLAG,ok,0.038427,0.008540,35236,0.033604,um,0.000001,9.000000e-09,...,8.404317e-09,1.303133e-08,317,936,6.286156e-09,0.167281,3.056070,2.05 MiB,None,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
4,PLAG242,PLAG,ok,0.039649,0.008695,15614,0.014891,um,0.000001,9.000000e-09,...,1.270388e-08,1.616766e-08,158,396,1.341178e-07,0.389785,1.580499,1.01 MiB,None,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,PLAG189,PLAG,ok,0.063722,0.024453,95521,0.091096,um,0.000001,9.000000e-09,...,8.918689e-09,1.362560e-08,841,2565,8.720410e-09,0.133358,6.187585,5.46 MiB,None,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
58,PLAG188,PLAG,ok,0.091994,0.024759,160874,0.153421,um,0.000001,9.000000e-09,...,9.952635e-09,1.416835e-08,1218,4522,1.316717e-08,0.178875,3.326095,8.02 MiB,None,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
59,PLAG187,PLAG,ok,0.090067,0.024917,159474,0.152086,um,0.000001,9.000000e-09,...,9.817991e-09,1.401865e-08,1206,4484,7.557061e-10,0.010985,556.251997,7.94 MiB,None,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
60,PLAG186,PLAG,ok,0.087993,0.025535,142646,0.136038,um,0.000001,9.000000e-09,...,1.000122e-08,1.478028e-08,1124,3965,1.238480e-08,0.136885,4.687332,7.37 MiB,None,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...
61,PLAG184,PLAG,ok,0.081315,0.025689,128058,0.122126,um,0.000001,9.000000e-09,...,9.700515e-09,1.457796e-08,1060,3508,1.216343e-08,0.174509,3.968541,6.92 MiB,None,/Users/yimingzhang/Github/stl2fem.jl/data/Niko...

In [9]:
ok = results[results["status"] == "ok"].sort_values("merrill_msh_size_bytes")
display_count = len(ok) if DISPLAY_LIMIT is None else min(DISPLAY_LIMIT, len(ok))
print(f"Displaying {display_count} of {len(ok)} converted meshes. Increase DISPLAY_LIMIT to inspect more.")

for _, row in ok.head(display_count).iterrows():
    print(f"{row['particle_id']}: {row['n_nodes']} nodes, {row['n_tets']} tets, {row['estimated_memory_human']} estimated Merrill.jl memory")
    if row.get("msh_path"):
        print(f"  native diagnostic mesh: {row['msh_path']}")
    print(f"  Merrill meters: {row.get('merrill_msh_path', '')}")
    display_volume_mesh(row["merrill_msh_path"], show_edges=True, opacity=0.35)

Displaying 62 of 62 converted meshes. Increase DISPLAY_LIMIT to inspect more.
PLAG225: 141 nodes, 369 tets, 929.29 KiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG225.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa2110_9&reconnect=auto" class="pyvista…

PLAG242: 158 nodes, 396 tets, 1.01 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG242.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa0bb0_10&reconnect=auto" class="pyvist…

PLAG246: 272 nodes, 776 tets, 1.76 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG246.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa3910_11&reconnect=auto" class="pyvist…

PLAG245: 283 nodes, 819 tets, 1.83 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG245.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa3d90_12&reconnect=auto" class="pyvist…

PLAG220: 293 nodes, 848 tets, 1.90 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG220.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa2a70_13&reconnect=auto" class="pyvist…

PLAG241: 293 nodes, 852 tets, 1.90 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG241.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa1fc0_14&reconnect=auto" class="pyvist…

PLAG244: 305 nodes, 871 tets, 1.97 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG244.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa2680_15&reconnect=auto" class="pyvist…

PLAG238: 307 nodes, 886 tets, 1.99 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG238.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa2410_16&reconnect=auto" class="pyvist…

PLAG243: 317 nodes, 936 tets, 2.05 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG243.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa2ce0_17&reconnect=auto" class="pyvist…

PLAG235: 302 nodes, 984 tets, 1.97 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG235.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa0a90_18&reconnect=auto" class="pyvist…

PLAG240: 349 nodes, 1034 tets, 2.26 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG240.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x16802c6a0_19&reconnect=auto" class="pyvist…

PLAG232: 359 nodes, 1067 tets, 2.33 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG232.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa04c0_20&reconnect=auto" class="pyvist…

PLAG233: 383 nodes, 1118 tets, 2.48 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG233.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x110236560_21&reconnect=auto" class="pyvist…

PLAG234: 394 nodes, 1150 tets, 2.55 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG234.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bbc2c20_22&reconnect=auto" class="pyvist…

PLAG226: 388 nodes, 1172 tets, 2.52 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG226.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bac3d90_23&reconnect=auto" class="pyvist…

PLAG227: 401 nodes, 1216 tets, 2.60 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG227.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bb75690_24&reconnect=auto" class="pyvist…

PLAG229: 423 nodes, 1266 tets, 2.74 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG229.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa56f0_25&reconnect=auto" class="pyvist…

PLAG239: 419 nodes, 1346 tets, 2.73 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG239.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baf63e0_26&reconnect=auto" class="pyvist…

PLAG230: 457 nodes, 1383 tets, 2.97 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG230.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x30b793520_27&reconnect=auto" class="pyvist…

PLAG228: 455 nodes, 1396 tets, 2.96 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG228.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baab0a0_28&reconnect=auto" class="pyvist…

PLAG237: 461 nodes, 1447 tets, 3.00 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG237.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x144a76da0_29&reconnect=auto" class="pyvist…

PLAG236: 454 nodes, 1479 tets, 2.96 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG236.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bac0f40_30&reconnect=auto" class="pyvist…

PLAG218: 498 nodes, 1447 tets, 3.22 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG218.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bb765c0_31&reconnect=auto" class="pyvist…

PLAG207: 460 nodes, 1518 tets, 3.00 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG207.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bc27a60_32&reconnect=auto" class="pyvist…

PLAG217: 494 nodes, 1497 tets, 3.21 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG217.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33ba6f340_33&reconnect=auto" class="pyvist…

PLAG221: 490 nodes, 1516 tets, 3.19 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG221.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bc26890_34&reconnect=auto" class="pyvist…

PLAG192: 512 nodes, 1570 tets, 3.33 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG192.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33babee00_35&reconnect=auto" class="pyvist…

PLAG216: 511 nodes, 1575 tets, 3.32 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG216.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bc27af0_36&reconnect=auto" class="pyvist…

PLAG231: 497 nodes, 1638 tets, 3.25 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG231.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bac0670_37&reconnect=auto" class="pyvist…

PLAG223: 525 nodes, 1617 tets, 3.41 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG223.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bb88400_38&reconnect=auto" class="pyvist…

PLAG210: 543 nodes, 1636 tets, 3.52 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG210.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa1540_39&reconnect=auto" class="pyvist…

PLAG219: 537 nodes, 1703 tets, 3.50 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG219.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bb384c0_40&reconnect=auto" class="pyvist…

PLAG206: 559 nodes, 1760 tets, 3.64 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG206.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x39ec217e0_41&reconnect=auto" class="pyvist…

PLAG212: 578 nodes, 1752 tets, 3.75 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG212.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33babde70_42&reconnect=auto" class="pyvist…

PLAG224: 542 nodes, 1804 tets, 3.54 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG224.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baabca0_43&reconnect=auto" class="pyvist…

PLAG215: 569 nodes, 1789 tets, 3.70 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG215.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33babc580_44&reconnect=auto" class="pyvist…

PLAG214: 601 nodes, 1796 tets, 3.90 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG214.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa2200_45&reconnect=auto" class="pyvist…

PLAG209: 652 nodes, 2065 tets, 4.25 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG209.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x39833bfa0_46&reconnect=auto" class="pyvist…

PLAG211: 650 nodes, 2130 tets, 4.24 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG211.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x16802c610_47&reconnect=auto" class="pyvist…

PLAG222: 631 nodes, 2162 tets, 4.13 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG222.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x39833bd90_48&reconnect=auto" class="pyvist…

PLAG199: 676 nodes, 2137 tets, 4.40 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG199.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3ad29a770_49&reconnect=auto" class="pyvist…

PLAG194: 726 nodes, 2215 tets, 4.72 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG194.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3a3fd39a0_50&reconnect=auto" class="pyvist…

PLAG205: 693 nodes, 2265 tets, 4.52 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG205.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3b5605e40_51&reconnect=auto" class="pyvist…

PLAG201: 693 nodes, 2297 tets, 4.53 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG201.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3a3fd2290_52&reconnect=auto" class="pyvist…

PLAG203: 739 nodes, 2432 tets, 4.82 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG203.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33bb89d80_53&reconnect=auto" class="pyvist…

PLAG197: 745 nodes, 2562 tets, 4.88 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG197.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3c4631810_54&reconnect=auto" class="pyvist…

PLAG202: 744 nodes, 2584 tets, 4.88 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG202.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3a3fd3970_55&reconnect=auto" class="pyvist…

PLAG204: 738 nodes, 2621 tets, 4.84 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG204.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x39ec22dd0_56&reconnect=auto" class="pyvist…

PLAG189: 841 nodes, 2565 tets, 5.46 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG189.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33ba6d030_57&reconnect=auto" class="pyvist…

PLAG213: 763 nodes, 2658 tets, 5.00 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG213.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3ad29beb0_58&reconnect=auto" class="pyvist…

PLAG208: 759 nodes, 2690 tets, 4.98 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG208.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x33baa2650_59&reconnect=auto" class="pyvist…

PLAG198: 832 nodes, 2851 tets, 5.45 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG198.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3bb946560_60&reconnect=auto" class="pyvist…

PLAG195: 920 nodes, 3139 tets, 6.02 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG195.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3d17b53c0_61&reconnect=auto" class="pyvist…

PLAG196: 926 nodes, 3202 tets, 6.07 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG196.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3b5607700_62&reconnect=auto" class="pyvist…

PLAG200: 924 nodes, 3354 tets, 6.08 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG200.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3d7983640_63&reconnect=auto" class="pyvist…

PLAG190: 981 nodes, 3518 tets, 6.44 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG190.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3c944baf0_64&reconnect=auto" class="pyvist…

PLAG184: 1060 nodes, 3508 tets, 6.92 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG184.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3dfe56830_65&reconnect=auto" class="pyvist…

PLAG191: 1083 nodes, 3924 tets, 7.12 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG191.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3ad298ee0_66&reconnect=auto" class="pyvist…

PLAG186: 1124 nodes, 3965 tets, 7.37 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG186.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3e98518d0_67&reconnect=auto" class="pyvist…

PLAG193: 1145 nodes, 4158 tets, 7.53 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG193.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3c944bc70_68&reconnect=auto" class="pyvist…

PLAG187: 1206 nodes, 4484 tets, 7.94 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG187.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3e9851930_69&reconnect=auto" class="pyvist…

PLAG188: 1218 nodes, 4522 tets, 8.02 MiB estimated Merrill.jl memory
  Merrill meters: /Users/yimingzhang/Github/stl2fem.jl/data/Nikolaisen2022_merrill_msh/PLAG188.msh

Widget(value='<iframe src="http://localhost:52926/index.html?ui=P_0x3d17b6cb0_70&reconnect=auto" class="pyvist…